seed = 13
bins = "__none__"

[data]
path = "data/microsoft"
T_cache = true
subsample = "__none__"

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 9
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
periodic = "__none__"
autodis = "__none__"
dice = true
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    654,
    353,
    353,
    353,
    353,
    579,
]
dropout = 0.4365594921159777

[training]
batch_size = 1024
lr = 6.222392345035965e-05
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
