seed = 6
bins = "__none__"

[data]
path = "data/fb-comments"
T_cache = true
subsample = "__none__"

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 67
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
periodic = "__none__"
autodis = "__none__"
dice = true
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    931,
    549,
]
dropout = 0.2026623992268599

[training]
batch_size = 512
lr = 6.302800734147664e-05
weight_decay = 0.0006991072099812656
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
